version: "3"
services:
  mysql-users:
    image: 'mysql:5.7'
    container_name: db-users3

    volumes:
      - ./data/db-users3:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"

  mysql-messages-shard1:
    image: 'mysql:5.7'
    container_name: db-messages-shard1
    volumes:
      - ./data/db-messages-shard1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - 3360:3306
  social-networks-chat:
    build: ./
    ports:
      - '8888:8888'
    volumes:
      - ./:/app
    depends_on:
      - mysql-messages-shard1
    environment:
      - PORT=8888
      - RUN_IN_DOCKER=1
      - USER_SERVICE=http://localhost:9999
      - DB_MESSAGES1_HOST=mysql-messages-shard1
      - DB_MESSAGES1_PORT=3306
      - DB_MESSAGES1_DATABASE=go-site
      - DB_MESSAGES1_USERNAME=root
      - DB_MESSAGES1_PASSWORD=secret
      - SQL_MAX_OPEN_CONNECT=5
      - SQL_MAX_IDLE_CONNECT=5
      - SQL_MAX_LIFE_CONNECT=3600
      - SECRET_KEY=54325432fds542543a
      - JWT_TOKEN_EXPIRES_MINUTE=50
  social-networks-user:
    build: ./
    ports:
      - '9999:9999'
    volumes:
      - ./:/app
    depends_on:
      - mysql-users
    environment:
      - PORT=9999
      - RUN_IN_DOCKER=1
      - DB_USERS_HOST=mysql-users
      - DB_USERS_PORT=3306
      - DB_USERS_DATABASE=go-site
      - DB_USERS_USERNAME=root
      - DB_USERS_PASSWORD=secret
      - SQL_MAX_OPEN_CONNECT=5
      - SQL_MAX_IDLE_CONNECT=5
      - SQL_MAX_LIFE_CONNECT=3600
      - SECRET_KEY=54325432fds542543a
      - JWT_TOKEN_EXPIRES_MINUTE=50